# fly.toml app configuration file generated for antidegen on 2024-11-03T18:40:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'antidegen'
primary_region = 'fra'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
